### PR TITLE
Remove deprecated

### PR DESCRIPTION
**Pull request by skalidindi3**
Just following the FIXME instruction...

### CODE REVIEW

**Comment by Numkil** [comment]
+1 I don't even know why they are actually there, not used.

**Comment by losingkeys** [comment]
Sorry, I meant to add a warning message when these options are used. I think we should add the warning and _then_ remove after 6 months.

**Comment by losingkeys** [comment]
Yeah sorry about the confusion. Meant to add that warning awhile ago.

**Comment by skalidindi3** [comment]
No worries

**Pull request closed without merging**
